{% set name = "sorcha-addons" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dirac-institute/sorcha-addons/archive/v{{ version }}.tar.gz
  sha256: 6f25e103a20ae70e88b08d3e622bc6022b634bf3e3b3659a736c54f1242bd724

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - pandas
    - numpy
    - sorcha >=0.6.0
    - astropy
    - scipy

test:
  imports:
    - sorcha_addons
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: src/sorcha_addons/activity/lsst_comet/LICENSE
  home: https://github.com/dirac-institute/sorcha-addons
  summary: Add-on modules for the Sorcha survey simulator

extra:
  recipe-maintainers:
    - mjuric
    - mschwamb
